package com.askrun.ai

import android.os.Bundle
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity

// Note: The 'R' class is generated by Android build tools.
// It will be resolved once these files are in an Android project.
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val webView: WebView = findViewById(R.id.webView)

        // Enable JavaScript, which is required for the chat UI to function
        webView.settings.javaScriptEnabled = true

        // Set a WebViewClient to keep navigation inside the app
        webView.webViewClient = WebViewClient()

        // Load the chatbot URL.
        // For production: Replace with your deployed Render URL.
        // For local testing in the Android emulator, "10.0.2.2" is a special
        // alias for your computer's localhost.
        webView.loadUrl("http://10.0.2.2:5000")
    }
}
